# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12blC1hBUnTVtICQsS4VwRS13q7rkEEjf
"""

import pandas as pd
from src.data_loader import load_and_clean_data
from src.features import build_features
from src.models import ForecastingOrchestrator
from src.explain import generate_shap_insights

def run_pipeline():
    print("=== Starting Inventory Forecasting Pipeline ===")

    # 1. Load data
    df = load_and_clean_data("data/raw/sales_data.csv")

    # 2. Engineer features
    df_featured = build_features(df)

    # 3. Time-based Train/Test Split (Avoid data leakage)
    split_date = df_featured['date'].max() - pd.Timedelta(days=30)
    train = df_featured[df_featured['date'] < split_date]
    test = df_featured[df_featured['date'] >= split_date]

    features = [col for col in df_featured.columns if col not in ['date', 'sales', 'item_id']]
    X_train, y_train = train[features], train['sales']
    X_test, y_test = test[features], test['sales']

    # 4. Train and Evaluate
    orchestrator = ForecastingOrchestrator()
    orchestrator.train_all(X_train, y_train)
    metrics = orchestrator.evaluate_all(X_test, y_test)

    print("\n=== Model Performance Metrics ===")
    print(metrics)

    # 5. Explainability via best performing model (e.g., LightGBM)
    print("\nGenerating model interpretations...")
    generate_shap_insights(orchestrator.models['lightgbm'], X_train)

if __name__ == "__main__":
    run_pipeline()