# -*- coding: utf-8 -*-
"""Src.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdKw9oQ5VbWG2AgCNoeeDmwheC5XxfRQ
"""

import pandas as pd

def load_and_clean_data(file_path: str) -> pd.DataFrame:
    """Loads raw sales data and ensures proper datetime parsing."""
    df = pd.read_csv(file_path)
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values('date').reset_index(drop=True)

    # Handle basic missing values safely using ffill() instead of fillna(method='ffill')
    df['sales'] = df['sales'].ffill()
    return df

import pandas as pd

def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """Generates time-series lag features, rolling windows, and calendar effects."""
    df = df.copy()

    # Calendar features
    df['month'] = df['date'].dt.month
    df['day_of_week'] = df['date'].dt.dayofweek
    df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)

    # Lag features (previous sales performance)
    for lag in [1, 7, 14, 30]:
        df[f'sales_lag_{lag}'] = df.groupby('item_id')['sales'].shift(lag)

    # Rolling statistics
    df['sales_rolling_mean_7'] = df.groupby('item_id')['sales'].transform(lambda x: x.shift(1).rolling(7).mean())
    df['sales_rolling_std_7'] = df.groupby('item_id')['sales'].transform(lambda x: x.shift(1).rolling(7).std())

    # Drop rows with NaN values introduced by lags
    return df.dropna().reset_index(drop=True)

!pip install catboost
import numpy as np
import pandas as pd
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

class ForecastingOrchestrator:
    def __init__(self):
        self.models = {
            'xgboost': XGBRegressor(n_estimators=100, learning_rate=0.05, random_state=42),
            'lightgbm': LGBMRegressor(n_estimators=100, learning_rate=0.05, random_state=42, verbose=-1),
            'catboost': CatBoostRegressor(iterations=100, learning_rate=00.05, random_state=42, verbose=0)
        }

    def train_all(self, X_train: pd.DataFrame, y_train: pd.Series):
        for name, model in self.models.items():
            print(f"Training {name}...")
            model.fit(X_train, y_train)

    def evaluate_all(self, X_test: pd.DataFrame, y_test: pd.Series) -> pd.DataFrame:
        results = {}
        for name, model in self.models.items():
            preds = model.predict(X_test)
            mae = mean_absolute_error(y_test, preds)
            rmse = np.sqrt(mean_squared_error(y_test, preds))
            mape = np.mean(np.abs((y_test - preds) / y_test)) * 100

            results[name] = {'MAE': mae, 'RMSE': rmse, 'MAPE (%)': mape}
        return pd.DataFrame(results).T

import shap
import pandas as pd
import matplotlib.pyplot as plt

def generate_shap_insights(model, X_train: pd.DataFrame):
    """Calculates and plots SHAP feature importance for model transparency."""
    # Use a sample of X_train for the background dataset to speed up SHAP calculation
    # and avoid the subsampling warning. Adjust sample size as needed.
    background_data = X_train.sample(n=min(500, len(X_train)), random_state=42)
    explainer = shap.Explainer(model, background_data)
    shap_values = explainer(X_train)

    # Generate summary plot (saves to disk for production logging)
    plt.figure(figsize=(10, 6))
    shap.summary_plot(shap_values, X_train, show=False)
    plt.tight_layout()
    plt.savefig('shap_summary.png')
    plt.close()
    print("SHAP feature importance plot saved as 'shap_summary.png'.")