# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdKw9oQ5VbWG2AgCNoeeDmwheC5XxfRQ
"""

import pandas as pd

def load_and_clean_data(file_path: str) -> pd.DataFrame:
    """Loads raw sales data and ensures proper datetime parsing."""
    df = pd.read_csv(file_path)
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values('date').reset_index(drop=True)

    # Handle basic missing values safely using ffill() instead of fillna(method='ffill')
    df['sales'] = df['sales'].ffill()
    return df