# -*- coding: utf-8 -*-
"""explain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdKw9oQ5VbWG2AgCNoeeDmwheC5XxfRQ
"""

import shap
import pandas as pd
import matplotlib.pyplot as plt

def generate_shap_insights(model, X_train: pd.DataFrame):
    """Calculates and plots SHAP feature importance for model transparency."""
    explainer = shap.Explainer(model, X_train)
    shap_values = explainer(X_train)

    # Generate summary plot (saves to disk for production logging)
    plt.figure(figsize=(10, 6))
    shap.summary_plot(shap_values, X_train, show=False)
    plt.tight_layout()
    plt.savefig('shap_summary.png')
    plt.close()
    print("SHAP feature importance plot saved as 'shap_summary.png'.")