# -*- coding: utf-8 -*-
"""features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdKw9oQ5VbWG2AgCNoeeDmwheC5XxfRQ
"""

import pandas as pd

def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """Generates time-series lag features, rolling windows, and calendar effects."""
    df = df.copy()

    # Calendar features
    df['month'] = df['date'].dt.month
    df['day_of_week'] = df['date'].dt.dayofweek
    df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)

    # Lag features (previous sales performance)
    for lag in [1, 7, 14, 30]:
        df[f'sales_lag_{lag}'] = df.groupby('item_id')['sales'].shift(lag)

    # Rolling statistics
    df['sales_rolling_mean_7'] = df.groupby('item_id')['sales'].transform(lambda x: x.shift(1).rolling(7).mean())
    df['sales_rolling_std_7'] = df.groupby('item_id')['sales'].transform(lambda x: x.shift(1).rolling(7).std())

    # Drop rows with NaN values introduced by lags
    return df.dropna().reset_index(drop=True)