# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdKw9oQ5VbWG2AgCNoeeDmwheC5XxfRQ
"""

import numpy as np
import pandas as pd
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

class ForecastingOrchestrator:
    def __init__(self):
        self.models = {
            'xgboost': XGBRegressor(n_estimators=100, learning_rate=0.05, random_state=42),
            'lightgbm': LGBMRegressor(n_estimators=100, learning_rate=0.05, random_state=42, verbose=-1),
            'catboost': CatBoostRegressor(iterations=100, learning_rate=0.05, random_state=42, verbose=0)
        }

    def train_all(self, X_train: pd.DataFrame, y_train: pd.Series):
        for name, model in self.models.items():
            print(f"Training {name}...")
            model.fit(X_train, y_train)

    def evaluate_all(self, X_test: pd.DataFrame, y_test: pd.Series) -> pd.DataFrame:
        results = {}
        for name, model in self.models.items():
            preds = model.predict(X_test)
            mae = mean_absolute_error(y_test, preds)
            rmse = np.sqrt(mean_squared_error(y_test, preds))
            mape = np.mean(np.abs((y_test - preds) / y_test)) * 100

            results[name] = {'MAE': mae, 'RMSE': rmse, 'MAPE (%)': mape}
        return pd.DataFrame(results).T